module.exports = {
  version: "0.2",
  language: "en,es",
  import: ["@cspell/dict-es-es/cspell-ext.json"],
  dictionaries: ["es-es"],
  ignorePaths: ["**/.next/**", "**/node_modules/**", "**/package-lock.json"],
  words: [
    "Mave",
    "MaveMed",
    "MaveMedical",
    "MedSpa",
    "Tijuana",
    "COFEPRIS",
    "Botox",
    "Dysport",
    "Xeomin",
    "Jeuveau",
    "Sculptra",
    "HarmonyCa",
    "Juvéderm",
    "Juvederm",
    "Volbella",
    "Volift",
    "Voluma",
    "Volux",
    "SkinVive",
    "Restylane",
    "Radiesse",
    "Kybella",
    "Belotero",
    "Sylfirm",
    "Ultraformer",
    "Rejuran",
    "Toskani",
    "HydraFacial",
    "Hydrafacial",
    "Casmara",
    "Alma",
    "Soprano",
    "Titanium",
    "Kenalog",
    "Kiara",
    "Reju",
    "Lumicen",
    "Stylage",
    "Infinity",
    "K-Láser",
    "Vortex-Fusión",
    "VortexFusion",
    "PRP",
    "PRFM",
    "PDRN",
    "PN",
    "PLLA",
    "CaHA",
    "HA",
    "PDO",
    "RF",
    "HIFU",
    "CO2",
    "Onabotulinum"
  ]
};
